/* Emits the exact bytes Node A puts on the wire for one telemetry cycle.
 *
 * The generator drives the same NodeATelemetry_FormatAll the board runs, so
 * the committed header is producer output rather than a hand-written fixture.
 * Rebuild it with tests/update_node_a_telemetry_vectors.sh; the ESP suite then
 * parses these bytes with the real CTRL-02 consumer, which is what keeps the
 * producer and consumer schemas from drifting apart again.
 *
 * Usage: node_a_telemetry_vectors [--check <path>]
 *   (no arguments)  print the header on stdout
 *   --check <path>  compare the generated header with <path>, non-zero on drift
 */
#include "node_a_telemetry.h"

#include <stdio.h>
#include <string.h>

static const SensorReading fixture_sensors[] = {
  { .asset_code = "SHT-01", .kind = SENSOR_KIND_SHT30, .quality = SENSOR_QUALITY_GOOD,
    .online = 1U, .temperature_centi_c = 2345, .humidity_centi_rh = 5210U },
  { .asset_code = "O2-01", .kind = SENSOR_KIND_O2, .quality = SENSOR_QUALITY_SUSPECT,
    .online = 1U, .raw = 812U, .microvolts = 654000UL },
  { .asset_code = "MQ4-01", .kind = SENSOR_KIND_MQ4, .quality = SENSOR_QUALITY_GOOD,
    .online = 1U, .raw = 0U, .microvolts = 0UL },
  { .asset_code = "CO-01", .kind = SENSOR_KIND_CO, .quality = SENSOR_QUALITY_SUSPECT,
    .online = 1U, .raw = 138U, .microvolts = 111000UL },
  { .asset_code = "MQ2-01", .kind = SENSOR_KIND_MQ2, .quality = SENSOR_QUALITY_GOOD,
    .online = 1U, .alarm = 0U },
  { .asset_code = "FLAME-01", .kind = SENSOR_KIND_FLAME, .quality = SENSOR_QUALITY_GOOD,
    .online = 1U, .alarm = 0U },
  { .asset_code = "LEVEL-01", .kind = SENSOR_KIND_LEVEL, .quality = SENSOR_QUALITY_GOOD,
    .online = 1U, .alarm = 0U }
};

static void build_snapshot(NodeATelemetrySnapshot *snapshot)
{
  (void)memset(snapshot, 0, sizeof(*snapshot));
  snapshot->sensors = fixture_sensors;
  snapshot->sensor_count = (uint8_t)(sizeof(fixture_sensors) / sizeof(fixture_sensors[0]));
  snapshot->environment.online = 1U;
  snapshot->environment.temperature_centi_c = 2345;      /* 23.45 degC */
  snapshot->environment.humidity_centi_rh = 5210U;       /* 52.10 %RH */
  snapshot->oxygen_raw = 812U;
  snapshot->oxygen_microvolts = 654000UL;                /* 654.000 mV */
  snapshot->oxygen_online = 1U;
  snapshot->methane_raw = 0U;
  snapshot->methane_microvolts = 0UL;
  snapshot->methane_online = 1U;
  snapshot->co_raw = 138U;
  snapshot->co_microvolts = 111000UL;                    /* 111.000 mV */
  snapshot->co_online = 1U;
  /* A normal cycle: no alarm, both fans running at the 60 percent preset the
   * menu offers, relay latched, white LED, buzzer armed. */
  snapshot->smoke_alarm = 0U;
  snapshot->flame_alarm = 0U;
  snapshot->level_detected = 0U;
  snapshot->smoke_sampled = 1U;
  snapshot->flame_sampled = 1U;
  snapshot->level_stable = 1U;
  snapshot->gas_warning = 0U;
  snapshot->gas_alarm = 0U;
  snapshot->oxygen_warning = 0U;
  snapshot->oxygen_alarm = 0U;
  snapshot->co_warning = 0U;
  snapshot->co_alarm = 0U;
  snapshot->fan1_power.online = 1U;
  snapshot->fan1_power.plausible = 1U;
  snapshot->fan1_power.fault = 0U;
  snapshot->fan1_power.bus_microvolts = 11900000UL;      /* 11.900 V */
  snapshot->fan1_power.current_microamps = 320000;       /* 320.000 mA */
  snapshot->fan1_power.power_microwatts = 3808000;       /* 3.808 W */
  snapshot->fan2_power.online = 1U;
  snapshot->fan2_power.plausible = 1U;
  snapshot->fan2_power.fault = 0U;
  snapshot->fan2_power.bus_microvolts = 11800000UL;      /* 11.800 V */
  snapshot->fan2_power.current_microamps = 280000;       /* 280.000 mA */
  snapshot->fan2_power.power_microwatts = 3304000;       /* 3.304 W */
  snapshot->fan1_rpm = 2400U;
  snapshot->fan2_rpm = 1600U;
  snapshot->actuators.fan1_pwm_percent = 60U;
  snapshot->actuators.fan2_pwm_percent = 60U;
  snapshot->actuators.relay_on = 1U;
  snapshot->actuators.buzzer_on = 0U;
  snapshot->actuators.buzzer_muted = 0U;
  snapshot->actuators.led_mode = 1U;
  snapshot->actuators.led_brightness_percent = 75U;
  snapshot->auto_ventilation_active = 0U;
  snapshot->cooldown_active = 0U;
}

static void generate(char frames[NODE_A_TELEMETRY_FRAME_COUNT][NODE_A_TELEMETRY_FRAME_SIZE],
                     uint16_t lengths[NODE_A_TELEMETRY_FRAME_COUNT])
{
  NodeATelemetrySnapshot snapshot;
  uint32_t sequence = 0U;
  build_snapshot(&snapshot);
  NodeATelemetry_FormatAll(&sequence, &snapshot, frames, lengths);
}

/* Emits the header in a fixed layout so regeneration is byte-stable. */
static int emit(FILE *out)
{
  char frames[NODE_A_TELEMETRY_FRAME_COUNT][NODE_A_TELEMETRY_FRAME_SIZE];
  uint16_t lengths[NODE_A_TELEMETRY_FRAME_COUNT] = {0U};
  uint8_t index;

  generate(frames, lengths);

  if (fprintf(out,
              "/* Generated by tests/node_a_telemetry_vectors.c -- do not edit.\n"
              " * These are the exact bytes Node A transmits for one cycle of the\n"
              " * fixture in that generator.  Regenerate with\n"
              " * tests/update_node_a_telemetry_vectors.sh. */\n"
              "#ifndef NODE_A_TELEMETRY_VECTORS_H\n"
              "#define NODE_A_TELEMETRY_VECTORS_H\n\n"
              "#define NODE_A_TELEMETRY_VECTOR_COUNT %uU\n\n"
              "static const char *const kNodeATelemetryVectors[] = {\n",
              (unsigned)NODE_A_TELEMETRY_FRAME_COUNT) < 0) {
    return 0;
  }
  for (index = 0U; index < NODE_A_TELEMETRY_FRAME_COUNT; ++index) {
    uint16_t offset;
    if (fprintf(out, "  \"") < 0) return 0;
    for (offset = 0U; offset < lengths[index]; ++offset) {
      const unsigned char byte = (unsigned char)frames[index][offset];
      if (byte == '"') {
        if (fputs("\\\"", out) < 0) return 0;
      } else if (byte == '\\') {
        if (fputs("\\\\", out) < 0) return 0;
      } else if (byte == '\r') {
        if (fputs("\\r", out) < 0) return 0;
      } else if (byte == '\n') {
        if (fputs("\\n", out) < 0) return 0;
      } else if (fputc((int)byte, out) == EOF) {
        return 0;
      }
    }
    if (fputs("\",\n", out) < 0) return 0;
  }
  return fputs("};\n\n#endif\n", out) >= 0;
}

static int check(const char *path)
{
  char expected[NODE_A_TELEMETRY_FRAME_COUNT][NODE_A_TELEMETRY_FRAME_SIZE];
  char actual[NODE_A_TELEMETRY_FRAME_COUNT][NODE_A_TELEMETRY_FRAME_SIZE];
  uint16_t expected_lengths[NODE_A_TELEMETRY_FRAME_COUNT] = {0U};
  uint16_t actual_lengths[NODE_A_TELEMETRY_FRAME_COUNT] = {0U};
  char line[1024];
  FILE *file = fopen(path, "rb");
  uint8_t index = 0U;
  uint16_t offset = 0U;

  if (file == NULL) {
    (void)fprintf(stderr, "cannot open %s\n", path);
    return 1;
  }
  generate(expected, expected_lengths);
  /* Nothing else parses the generated file, so a light-weight scan for the
   * vector literals is enough to detect drift. */
  while (fgets(line, (int)sizeof(line), file) != NULL) {
    const char *start = strchr(line, '"');
    const char *end;
    if (start == NULL) continue;
    ++start;
    end = strrchr(start, '"');
    if ((end == NULL) || (end <= start)) continue;
    if (index >= NODE_A_TELEMETRY_FRAME_COUNT) break;
    for (offset = 0U; (start + offset) < end; ++offset) {
      char byte = start[offset];
      if (byte != '\\') {
        actual[index][actual_lengths[index]++] = byte;
        continue;
      }
      ++offset;
      switch (start[offset]) {
        case 'r': actual[index][actual_lengths[index]++] = '\r'; break;
        case 'n': actual[index][actual_lengths[index]++] = '\n'; break;
        case '\\': actual[index][actual_lengths[index]++] = '\\'; break;
        case '"': actual[index][actual_lengths[index]++] = '"'; break;
        default: break;
      }
    }
    ++index;
  }
  (void)fclose(file);
  if (index != NODE_A_TELEMETRY_FRAME_COUNT) {
    (void)fprintf(stderr, "vector file has %u frames, expected %u\n",
                  (unsigned)index, (unsigned)NODE_A_TELEMETRY_FRAME_COUNT);
    return 1;
  }
  for (index = 0U; index < NODE_A_TELEMETRY_FRAME_COUNT; ++index) {
    if ((actual_lengths[index] != expected_lengths[index]) ||
        (memcmp(actual[index], expected[index], expected_lengths[index]) != 0)) {
      (void)fprintf(stderr, "frame %u drifted from the committed vector\n",
                    (unsigned)index);
      return 1;
    }
  }
  return 0;
}

int main(int argc, char **argv)
{
  if ((argc == 3) && (strcmp(argv[1], "--check") == 0)) return check(argv[2]);
  if (argc != 1) {
    (void)fprintf(stderr, "usage: %s [--check <path>]\n", argv[0]);
    return 2;
  }
  return emit(stdout) ? 0 : 1;
}
