[platformio]
default_envs = esp01_ctrl01

[env:native]
platform = native
test_build_src = yes
build_src_filter = +<screen_protocol.cpp> +<screen_routing.cpp>

[env:esp01_base]
platform = espressif8266@4.2.1
board = esp01_1m
framework = arduino
monitor_speed = 9600
upload_speed = 115200
board_build.flash_mode = dout
lib_deps =
  knolleary/PubSubClient@^2.8
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

[env:esp01_ctrl01]
extends = env:esp01_base
build_flags =
  ${env:esp01_base.build_flags}
  -D BUILD_DEVICE_ID=\"CTRL-01\"
  -D BUILD_ROLE_CTRL01=1

[env:esp01_ctrl02]
extends = env:esp01_base
build_flags =
  ${env:esp01_base.build_flags}
  -D BUILD_DEVICE_ID=\"CTRL-02\"
  -D BUILD_ROLE_CTRL02=1
