[platformio]
default_envs = esp01_1m

[env:esp01_1m]
platform = espressif8266@4.2.1
board = esp01_1m
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dout
lib_deps =
  knolleary/PubSubClient@^2.8
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

