# Generated by Django 4.2.26 on 2026-08-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-opened_at'], name='alert_status_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['asset', 'status'], name='alert_asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-occurred_at'], name='audit_action_time_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['asset', '-recorded_at'], name='telemetry_asset_time_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', '-updated_at'], name='wo_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['asset', 'status'], name='wo_asset_status_idx'),
        ),
    ]
