# Generated by Django 4.2.26 on 2026-08-27 07:38

from django.db import migrations, models
from django.db.models import Count


def check_source_alert_duplicates(apps, schema_editor):
    WorkOrder = apps.get_model('operations', 'WorkOrder')
    duplicate = (
        WorkOrder.objects.filter(source_alert__isnull=False)
        .values('source_alert_id')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
        .order_by('source_alert_id')
        .first()
    )
    if duplicate:
        raise RuntimeError(
            'Cannot apply work_order_source_alert_unique: duplicate source_alert_id '
            f"{duplicate['source_alert_id']} exists. Resolve duplicates before migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alert_alert_status_opened_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(check_source_alert_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('source_alert__isnull', False)), fields=('source_alert',), name='work_order_source_alert_unique'),
        ),
    ]
