# Generated by Django 4.2.26 on 2026-08-27 07:40

from django.db import migrations, models
from django.db.models import F, Q


def check_threshold_values(apps, schema_editor):
    Threshold = apps.get_model('operations', 'Threshold')
    invalid = Threshold.objects.filter(Q(warning__lt=0) | Q(alarm__lte=F('warning'))).values('key').first()
    if invalid:
        raise RuntimeError(
            'Cannot apply threshold constraints: invalid values exist for '
            f"threshold '{invalid['key']}'. Fix warning/alarm before migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_workorder_work_order_source_alert_unique'),
    ]

    operations = [
        migrations.RunPython(check_threshold_values, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='threshold',
            constraint=models.CheckConstraint(check=models.Q(('warning__gte', 0)), name='threshold_warning_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='threshold',
            constraint=models.CheckConstraint(check=models.Q(('alarm__gt', models.F('warning'))), name='threshold_alarm_above_warning'),
        ),
    ]
