# Generated by Django 4.2.26 on 2026-08-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_threshold_threshold_warning_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexport',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
    ]
