# Generated by Django 4.2.26 on 2026-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_reportexport_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='asset',
            name='hardware_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='installation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='integration_status',
            field=models.CharField(choices=[('verified', '已验证'), ('firmware_connected', '固件已接入'), ('calibration_required', '待标定'), ('pending_verification', '待验证'), ('optional', '可选模块'), ('non_operational', '非运行资产')], default='pending_verification', max_length=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='interface',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='asset',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='location_source',
            field=models.CharField(choices=[('unassigned', '未配置'), ('demo_anchor', '演示锚点'), ('configured', '人工配置'), ('surveyed', '现场测绘'), ('gps', 'GPS 定位')], default='unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['zone', 'integration_status'], name='asset_zone_integration_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='asset_coordinates_paired'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='asset_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='asset_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('latitude__isnull', True), ('location_source', 'unassigned'), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False), models.Q(('location_source', 'unassigned'), _negated=True)), _connector='OR'), name='asset_location_source_consistent'),
        ),
    ]
