# Generated by Django 4.2.26 on 2026-08-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_asset_capabilities_asset_hardware_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
