# Generated by Django 4.2.26 on 2026-08-27 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_asset_is_active_asset_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_observed_value',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='rule_key',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='event_id',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='ingested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='metric_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['metric_key', '-recorded_at'], name='telemetry_metric_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('rule_key__isnull', False), ('status__in', ['open', 'acknowledged'])), fields=('asset', 'rule_key'), name='alert_active_rule_unique'),
        ),
    ]
