# Generated by Django 4.2.26 on 2026-08-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alert_last_observed_value_alert_rule_key_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['asset', 'metric_key', '-recorded_at'], name='telemetry_asset_metric_idx'),
        ),
    ]
