# Generated by Django 4.2.26 on 2026-08-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_telemetry_telemetry_asset_metric_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('mqtt', 'MQTT'), ('http', 'HTTP'), ('serial', '串口网关'), ('manual', '人工登记')], max_length=12)),
                ('device_identifier', models.CharField(max_length=80, unique=True)),
                ('endpoint', models.CharField(max_length=200)),
                ('expected_interval_seconds', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('reserved', '接口已预留'), ('connected', '已接入'), ('inactive', '未启用'), ('error', '接入异常')], default='reserved', max_length=20)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset__code'],
            },
        ),
        migrations.CreateModel(
            name='SpatialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('layer_type', models.CharField(choices=[('tunnel_segment', '管廊区段'), ('chamber', '舱室'), ('manhole', '井口'), ('inspection_route', '巡检路线'), ('risk_zone', '风险区域'), ('installation_point', '安装点')], max_length=30)),
                ('geometry', models.JSONField(default=dict)),
                ('crs', models.CharField(default='EPSG:4326', max_length=20)),
                ('source', models.CharField(choices=[('surveyed', '现场测绘'), ('cad_import', 'CAD/GIS 导入'), ('configured', '人工配置')], max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=180)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '待审核'), ('published', '已发布'), ('retired', '已退役')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['layer_type', 'code'],
                'indexes': [models.Index(fields=['layer_type', 'status'], name='spatial_layer_status_idx'), models.Index(fields=['status', '-updated_at'], name='spatial_status_updated_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='spatialfeature',
            constraint=models.CheckConstraint(check=models.Q(('crs', 'EPSG:4326')), name='spatial_wgs84_only'),
        ),
        migrations.AddConstraint(
            model_name='spatialfeature',
            constraint=models.CheckConstraint(check=models.Q(('accuracy_m__isnull', True), ('accuracy_m__gt', 0), _connector='OR'), name='spatial_accuracy_positive'),
        ),
        migrations.AddField(
            model_name='hardwarebinding',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_binding', to='operations.asset'),
        ),
        migrations.AddIndex(
            model_name='hardwarebinding',
            index=models.Index(fields=['status', '-last_heartbeat_at'], name='binding_status_heartbeat_idx'),
        ),
        migrations.AddConstraint(
            model_name='hardwarebinding',
            constraint=models.CheckConstraint(check=models.Q(('expected_interval_seconds__gte', 1), ('expected_interval_seconds__lte', 86400)), name='binding_interval_range'),
        ),
    ]
