# Generated by Django 4.2.26 on 2026-08-29

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_registrationrequest_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(
                Lower('mesh'),
                condition=~models.Q(mesh=''),
                name='asset_mesh_name_unique_ci',
            ),
        ),
    ]
