# Generated by Django 4.2.30 on 2026-08-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_asset_mesh_name_unique_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('administrator', '管理员'), ('operator', '运维员'), ('viewer', '查看者'), ('ingest', '遥测接入服务')], default='operator', max_length=20),
        ),
    ]
