# Generated by Django 4.2.30 on 2026-08-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='password_set_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='setup_expires_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='setup_token_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
