# Generated by Django 5.2.17 on 2026-09-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_reportexport_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='quality',
            field=models.CharField(choices=[('good', '良好'), ('suspect', '可疑'), ('bad', '异常'), ('missing', '缺失')], default='suspect', max_length=20),
        ),
    ]
