from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "Core" / "Inc" / "hmi_zh_font.h"
TEXT = (
    "系统菜单安全总览分类监测报警中心风机控制灯带与蜂鸣器通信状态系统设置"
    "安全预警报警环境气体积水火情风机供电两台联动启动全部停止"
    "确认操作发送中已执行失败显示摇杆"
)


def load_font():
    for candidate in (
        Path(r"C:\Windows\Fonts\msyh.ttc"),
        Path(r"C:\Windows\Fonts\simhei.ttf"),
    ):
        if candidate.exists():
            return ImageFont.truetype(str(candidate), 16)
    raise RuntimeError("No Chinese font found on this computer")


def glyph_bytes(character: str, font) -> list[int]:
    image = Image.new("1", (16, 16), 0)
    draw = ImageDraw.Draw(image)
    box = draw.textbbox((0, 0), character, font=font)
    width, height = box[2] - box[0], box[3] - box[1]
    draw.text(((16 - width) // 2 - box[0], (16 - height) // 2 - box[1]), character, font=font, fill=1)
    data: list[int] = []
    for y in range(16):
        for block in range(2):
            value = 0
            for bit in range(8):
                if image.getpixel((block * 8 + bit, y)):
                    value |= 0x80 >> bit
            data.append(value)
    return data


def main():
    font = load_font()
    lines = [
        "/* Auto-generated by tools/generate_hmi_zh_font.py. Do not edit manually. */",
        "#ifndef HMI_ZH_FONT_H",
        "#define HMI_ZH_FONT_H",
        "#include <stdint.h>",
        "typedef struct { uint16_t codepoint; uint8_t bitmap[32]; } HmiZhGlyph;",
        "static const HmiZhGlyph HMI_ZH_GLYPHS[] = {",
    ]
    for character in dict.fromkeys(TEXT):
        values = ", ".join(f"0x{byte:02X}" for byte in glyph_bytes(character, font))
        lines.append(f"  {{ 0x{ord(character):04X}, {{ {values} }} }}, /* {character} */")
    lines.extend(
        [
            "};",
            "#define HMI_ZH_GLYPH_COUNT (sizeof(HMI_ZH_GLYPHS) / sizeof(HMI_ZH_GLYPHS[0]))",
            "#endif /* HMI_ZH_FONT_H */",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
