from django.urls import path
from .views import AdminRegistrationRequestDetailView, AdminRegistrationRequestListView, AdminUserDetailView, AdminUserListView, AlertAcknowledgeView, AlertListView, AlertWorkOrderView, AssetDetailView, AssetListView, AuditListView, DashboardView, HardwareBindingDetailView, HardwareBindingListView, HealthView, LoginView, LogoutView, MeView, ReadyView, RegistrationRequestView, ReportExportView, SpatialFeatureDetailView, SpatialFeatureImportView, SpatialFeatureListView, TelemetryListView, TelemetrySummaryView, ThresholdDetailView, ThresholdListView, TwinModelReadinessView, WorkOrderListView, WorkOrderTransitionView


urlpatterns = [
    path('health/', HealthView.as_view()),
    path('ready/', ReadyView.as_view()),
    path('auth/login/', LoginView.as_view()),
    path('auth/registration-requests/', RegistrationRequestView.as_view()),
    path('auth/me/', MeView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path('admin/users/', AdminUserListView.as_view()),
    path('admin/users/<int:pk>/', AdminUserDetailView.as_view()),
    path('admin/registration-requests/', AdminRegistrationRequestListView.as_view()),
    path('admin/registration-requests/<int:pk>/', AdminRegistrationRequestDetailView.as_view()),
    path('dashboard/', DashboardView.as_view()),
    path('twin/model-readiness/', TwinModelReadinessView.as_view()),
    path('assets/', AssetListView.as_view()),
    path('assets/<int:pk>/', AssetDetailView.as_view()),
    path('gis/features/', SpatialFeatureListView.as_view()),
    path('gis/features/import/', SpatialFeatureImportView.as_view()),
    path('gis/features/<int:pk>/', SpatialFeatureDetailView.as_view()),
    path('hardware-bindings/', HardwareBindingListView.as_view()),
    path('hardware-bindings/<int:pk>/', HardwareBindingDetailView.as_view()),
    path('alerts/', AlertListView.as_view()),
    path('alerts/<int:pk>/acknowledge/', AlertAcknowledgeView.as_view()),
    path('alerts/<int:pk>/work-order/', AlertWorkOrderView.as_view()),
    path('work-orders/', WorkOrderListView.as_view()),
    path('work-orders/<int:pk>/transition/', WorkOrderTransitionView.as_view()),
    path('telemetry/', TelemetryListView.as_view()),
    path('telemetry/summary/', TelemetrySummaryView.as_view()),
    path('thresholds/', ThresholdListView.as_view()),
    path('thresholds/<str:key>/', ThresholdDetailView.as_view()),
    path('audit/', AuditListView.as_view()),
    path('report-exports/', ReportExportView.as_view()),
]
